// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: rpc/simple_osmosis_explorer.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBlocksByProposerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *GetBlocksByProposerRequest) Reset() {
	*x = GetBlocksByProposerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_simple_osmosis_explorer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlocksByProposerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlocksByProposerRequest) ProtoMessage() {}

func (x *GetBlocksByProposerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_simple_osmosis_explorer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlocksByProposerRequest.ProtoReflect.Descriptor instead.
func (*GetBlocksByProposerRequest) Descriptor() ([]byte, []int) {
	return file_rpc_simple_osmosis_explorer_proto_rawDescGZIP(), []int{0}
}

func (x *GetBlocksByProposerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockId         string                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Hash            string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Height          int64                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	ProposerAddress string                 `protobuf:"bytes,4,opt,name=proposer_address,json=proposerAddress,proto3" json:"proposer_address,omitempty"`
	Time            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	Txs             string                 `protobuf:"bytes,6,opt,name=txs,proto3" json:"txs,omitempty"`
	NumTxs          int64                  `protobuf:"varint,7,opt,name=num_txs,json=numTxs,proto3" json:"num_txs,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_simple_osmosis_explorer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_simple_osmosis_explorer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_rpc_simple_osmosis_explorer_proto_rawDescGZIP(), []int{1}
}

func (x *Block) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *Block) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Block) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Block) GetProposerAddress() string {
	if x != nil {
		return x.ProposerAddress
	}
	return ""
}

func (x *Block) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Block) GetTxs() string {
	if x != nil {
		return x.Txs
	}
	return ""
}

func (x *Block) GetNumTxs() int64 {
	if x != nil {
		return x.NumTxs
	}
	return 0
}

type GetBlocksByProposerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blocks []*Block `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
}

func (x *GetBlocksByProposerResponse) Reset() {
	*x = GetBlocksByProposerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_simple_osmosis_explorer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlocksByProposerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlocksByProposerResponse) ProtoMessage() {}

func (x *GetBlocksByProposerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_simple_osmosis_explorer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlocksByProposerResponse.ProtoReflect.Descriptor instead.
func (*GetBlocksByProposerResponse) Descriptor() ([]byte, []int) {
	return file_rpc_simple_osmosis_explorer_proto_rawDescGZIP(), []int{2}
}

func (x *GetBlocksByProposerResponse) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

var File_rpc_simple_osmosis_explorer_proto protoreflect.FileDescriptor

var file_rpc_simple_osmosis_explorer_proto_rawDesc = []byte{
	0x0a, 0x21, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x69, 0x73, 0x5f, 0x65, 0x78, 0x70, 0x6c, 0x6f, 0x72, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x1a, 0x47, 0x65, 0x74,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x22, 0xd4, 0x01, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x19, 0x0a, 0x08, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x72,
	0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2e, 0x0a,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x78, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x78, 0x73, 0x12,
	0x17, 0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x5f, 0x74, 0x78, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x6e, 0x75, 0x6d, 0x54, 0x78, 0x73, 0x22, 0x41, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x32, 0x71, 0x0a, 0x15, 0x53,
	0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4f, 0x73, 0x6d, 0x6f, 0x73, 0x69, 0x73, 0x45, 0x78, 0x70, 0x6c,
	0x6f, 0x72, 0x65, 0x72, 0x12, 0x58, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x73, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x42, 0x79, 0x50, 0x72, 0x6f,
	0x70, 0x6f, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x42, 0x79, 0x50, 0x72,
	0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06,
	0x5a, 0x04, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_simple_osmosis_explorer_proto_rawDescOnce sync.Once
	file_rpc_simple_osmosis_explorer_proto_rawDescData = file_rpc_simple_osmosis_explorer_proto_rawDesc
)

func file_rpc_simple_osmosis_explorer_proto_rawDescGZIP() []byte {
	file_rpc_simple_osmosis_explorer_proto_rawDescOnce.Do(func() {
		file_rpc_simple_osmosis_explorer_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_simple_osmosis_explorer_proto_rawDescData)
	})
	return file_rpc_simple_osmosis_explorer_proto_rawDescData
}

var file_rpc_simple_osmosis_explorer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpc_simple_osmosis_explorer_proto_goTypes = []interface{}{
	(*GetBlocksByProposerRequest)(nil),  // 0: rpc.GetBlocksByProposerRequest
	(*Block)(nil),                       // 1: rpc.Block
	(*GetBlocksByProposerResponse)(nil), // 2: rpc.GetBlocksByProposerResponse
	(*timestamppb.Timestamp)(nil),       // 3: google.protobuf.Timestamp
}
var file_rpc_simple_osmosis_explorer_proto_depIdxs = []int32{
	3, // 0: rpc.Block.time:type_name -> google.protobuf.Timestamp
	1, // 1: rpc.GetBlocksByProposerResponse.blocks:type_name -> rpc.Block
	0, // 2: rpc.SimpleOsmosisExplorer.GetBlocksByProposer:input_type -> rpc.GetBlocksByProposerRequest
	2, // 3: rpc.SimpleOsmosisExplorer.GetBlocksByProposer:output_type -> rpc.GetBlocksByProposerResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_simple_osmosis_explorer_proto_init() }
func file_rpc_simple_osmosis_explorer_proto_init() {
	if File_rpc_simple_osmosis_explorer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_simple_osmosis_explorer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlocksByProposerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_simple_osmosis_explorer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_simple_osmosis_explorer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlocksByProposerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_simple_osmosis_explorer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_simple_osmosis_explorer_proto_goTypes,
		DependencyIndexes: file_rpc_simple_osmosis_explorer_proto_depIdxs,
		MessageInfos:      file_rpc_simple_osmosis_explorer_proto_msgTypes,
	}.Build()
	File_rpc_simple_osmosis_explorer_proto = out.File
	file_rpc_simple_osmosis_explorer_proto_rawDesc = nil
	file_rpc_simple_osmosis_explorer_proto_goTypes = nil
	file_rpc_simple_osmosis_explorer_proto_depIdxs = nil
}
